// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_400.tsx";
import * as $1 from "./routes/browse/[name].tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/search.tsx";
import * as $4 from "./routes/submit.tsx";

const manifest = {
  routes: {
    "./routes/_400.tsx": $0,
    "./routes/browse/[name].tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/search.tsx": $3,
    "./routes/submit.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
