name: Code checks

on:
  push:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.6.0'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck
